// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.habibu.model.dod;

import com.habibu.model.City;
import com.habibu.model.dod.CityFactory;

privileged aspect CityFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link City} with the given index.
     * 
     * @param index position of the City
     * @return a new transient City
     */
    public City CityFactory.create(int index) {
        City obj = new City();
        return obj;
    }
    
}
