// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.habibu.model;

import com.habibu.model.City;
import io.springlets.format.EntityFormat;
import javax.persistence.Entity;

privileged aspect City_Roo_Jpa_Entity {
    
    declare @type: City: @Entity;
    
    declare @type: City: @EntityFormat;
    
}
