// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.habibu.model;

import com.habibu.model.CustomerOrderFormBean;
import io.springlets.format.EntityFormat;

privileged aspect CustomerOrderFormBean_Roo_DTO {
    
    declare @type: CustomerOrderFormBean: @EntityFormat;
    
}
