// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.habibu.application.web;

import com.habibu.application.web.CountriesItemRegionsThymeleafControllerIT;
import com.habibu.model.dod.CountryFactory;
import com.habibu.service.api.CountryService;
import com.habibu.service.api.CustomerOrderService;
import com.habibu.service.api.PartyService;
import com.habibu.service.api.RegionService;
import com.habibu.service.api.StoreService;
import com.habibu.service.api.SupplierService;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect CountriesItemRegionsThymeleafControllerIT_Roo_ThymeleafControllerIntegrationTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    public MockMvc CountriesItemRegionsThymeleafControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public CountryService CountriesItemRegionsThymeleafControllerIT.countryServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public CustomerOrderService CountriesItemRegionsThymeleafControllerIT.customerOrderServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public PartyService CountriesItemRegionsThymeleafControllerIT.partyServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public RegionService CountriesItemRegionsThymeleafControllerIT.regionServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public StoreService CountriesItemRegionsThymeleafControllerIT.storeServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public SupplierService CountriesItemRegionsThymeleafControllerIT.supplierServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public CountryFactory CountriesItemRegionsThymeleafControllerIT.factory = new CountryFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc CountriesItemRegionsThymeleafControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CountryService
     */
    public CountryService CountriesItemRegionsThymeleafControllerIT.getCountryServiceService() {
        return countryServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CustomerOrderService
     */
    public CustomerOrderService CountriesItemRegionsThymeleafControllerIT.getCustomerOrderServiceService() {
        return customerOrderServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PartyService
     */
    public PartyService CountriesItemRegionsThymeleafControllerIT.getPartyServiceService() {
        return partyServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return RegionService
     */
    public RegionService CountriesItemRegionsThymeleafControllerIT.getRegionServiceService() {
        return regionServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return StoreService
     */
    public StoreService CountriesItemRegionsThymeleafControllerIT.getStoreServiceService() {
        return storeServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return SupplierService
     */
    public SupplierService CountriesItemRegionsThymeleafControllerIT.getSupplierServiceService() {
        return supplierServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CountryFactory
     */
    public CountryFactory CountriesItemRegionsThymeleafControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void CountriesItemRegionsThymeleafControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
