// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.habibu.application.web;

import com.habibu.application.web.OrderDetailsCollectionThymeleafControllerIT;
import com.habibu.model.dod.OrderDetailFactory;
import com.habibu.service.api.OrderDetailService;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect OrderDetailsCollectionThymeleafControllerIT_Roo_ThymeleafControllerIntegrationTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    public MockMvc OrderDetailsCollectionThymeleafControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public OrderDetailService OrderDetailsCollectionThymeleafControllerIT.orderDetailServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public OrderDetailFactory OrderDetailsCollectionThymeleafControllerIT.factory = new OrderDetailFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc OrderDetailsCollectionThymeleafControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return OrderDetailService
     */
    public OrderDetailService OrderDetailsCollectionThymeleafControllerIT.getOrderDetailServiceService() {
        return orderDetailServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return OrderDetailFactory
     */
    public OrderDetailFactory OrderDetailsCollectionThymeleafControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void OrderDetailsCollectionThymeleafControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
